### ISSUE TITLE
Problem with triangle example

### ISSUE THREAD

**Issue by Cldfire** [tomaka/vulkano#122]
```
let pipeline = GraphicsPipeline::new(&device, GraphicsPipelineParams {
        // We need to indicate the layout of the vertices.
        // The type `SingleBufferDefinition` actually contains a template parameter corresponding
        // to the type of each vertex. But in this code it is automatically inferred.
        vertex_input: SingleBufferDefinition::new(),
```
I'm getting this error when trying to compile:
```
error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
      vertex_input: SingleBufferDefinition::new(),
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm using Rust 1.9 and Vulkano straight from this repo.

**Comment by tomaka** [comment]
It compiles fine for me. Also travis compiles the examples every time, so it should stop whenever they break.

Did you remove some code from the example? Because the template parameter of `SingleBufferDefinition` is automatically inferred from the fact that you pass a buffer that contains `[Vertex]` when `draw()` is called.

**Comment by Cldfire** [comment]
Oh, that would be my issue then. I haven't done anything that calls 'draw()' yet (trying to write the example out and learn from it rather than just copy + pasting).

I figured it was probably me being stupid, my apologies :)
