### ISSUE TITLE
Support for macOS via MoltenVK

### ISSUE THREAD

**Issue by RobertWHurst** [tomaka/vulkano#300]
Molten has released a Vulkan -> Metal adapter framework for macOS. Is there any chance we will see Vulkano use the MoltenVK framework if present on the system?
https://moltengl.com/moltenvk/

**Comment by tomaka** [comment]
I'm all for it, but I don't have any Mac machine so there's no way for me to implement it/test it.

**Comment by tomaka** [comment]
If MoltenVK is just a shared object, then it's just a small tweak here: https://github.com/tomaka/vulkano/blob/c8bf001ea112932d383b486fae66ae66146c5710/vulkano/src/instance/loader.rs#L20-L27

**Comment by tomaka** [comment]
I analyzed that stuff a little bit.

We need to add support for two extensions `VK_MVK_moltenvk` and `VK_MVK_macos_surface` in vk-sys and in vulkano. I'm not a fan of adding non-official extensions, but I can live with it. Most notably, the `VK_MVK_moltenvk` extension is required because you need to submit your paid license to the framework.

Then there's the question of how to link to the MoltenVK framework. I don't know enough about how OSX/iOS frameworks work to answer that.

**Comment by paulirotta** [comment]
You've never asked, but given how much you've done for the community...

Do you mind if we run an Indigogo or similar fundraising campaign to give you a Mac? Call it a selfish gift. I haven't done this before, so advice and ideas are welcome.

**Comment by tomaka** [comment]
Heh, that's nice but I don't want a Mac.
We just need someone who knows how to dlopen a framework, and then someone to test that it works.
The tweaks to vk-sys and vulkano can be made without a Mac (since it's just about translating C code into Rust).

**Comment by tomaka** [comment]
I forgot to mention `VK_MVK_ios_surface` with must also be added.

**Comment by RobertWHurst** [comment]
Very interesting. I'm willing to help with any testing or coding you may need. I'll look up how to load a macOS framework in Rust

**Comment by tomaka** [comment]
https://github.com/tomaka/vulkano/pull/301

**Comment by tomaka** [comment]
Closing as #301 as been merged.
Cc #490 though.
