### ISSUE TITLE
Count the number of allocations for maxMemoryAllocationCount

### ISSUE THREAD

**Issue by tomaka** [tomaka/vulkano#588]
I thought the driver would return a `VK_ERROR_TOO_MANY_OBJECTS`, but the validity section of `vkAllocateMemory` says that you must make sure you don't exceed `maxMemoryAllocationCount`.

**Comment by nicokoch** [comment]
Hey, I implemented a fix in https://github.com/nicokoch/vulkano/commit/ff0a0718c5e1e1c173ff37fcd76bb2f9d59b8556

Would you mind taking a look and see if the approach works for you?

**Comment by tomaka** [comment]
@nicokoch Oh, thanks. The tracking should be the `Device` and not in the `Instance`. Also it should preferably be a `AtomicUsize` and not use a Mutex. Using a `pub(crate)` function is the right approach I think.

**Comment by nicokoch** [comment]
@tomaka AtomicUsize doesn't really work, because we have to lock the entire allocation (otherwise allocation_count could be modified by another thread during the allocation).

Reasoning for tracking in PhysicalDevice: It's a PhysicalDeviceLimit after all. If you create multiple Devices for a single PhysicalDevice, your suggested approach doesn't really work (I'm not 100% sure about this)

**Comment by tomaka** [comment]
> Reasoning for tracking in PhysicalDevice: It's a PhysicalDeviceLimit after all. If you create multiple Devices for a single PhysicalDevice, your suggested approach doesn't really work (I'm not 100% sure about this)

All the limits apply to devices, not physical devices.
