### ISSUE TITLE
Blocking wait for buffer access

### ISSUE THREAD

**Issue by fst3a** [tomaka/vulkano#592]
Hello,

in 0.5.0 release CpuAccessibleBuffer::read and ::write methods do not block anymore but rather return immediately with failure if buffer can not be immediately locked.  Having blocking was useful for cases when there is another thread writing and/or reading to the buffer repeatedly submitted to GPU.  Are there plans to reintroduce blocking in some way or should user use spinning wait instead?

**Comment by tomaka** [comment]
The way resources locking changed (since 0.4 in fact), and the `CpuAccessibleBuffer` is no longer aware of the `Fence` that it needs to wait upon. Therefore there's no way for the buffer to wait until it is no longer in use by the GPU.

In fact one thing that can be confusing is that spin locking doesn't work either. You have to destroy the future object that contains the submission that uses the buffer.

**Comment by fst3a** [comment]
I see, thanks

**Comment by fst3a** [comment]
Actually, what is the way you would recommend for reading and writing large buffers now?  Does one just have to drop the future?

**Comment by tomaka** [comment]
Yes you have to explicitly know when the submission is finished, and then only call `read` or `write`.

**Comment by fst3a** [comment]
Thanks a lot
