### ISSUE TITLE
Fence::reset and Fence::multi_reset do not return OomError

### ISSUE THREAD

**Issue by nicokoch** [tomaka/vulkano#645]
The vulkan spec states that vkResetFences can result in OUT_OF_*_MEMORY

**Comment by nicokoch** [comment]
If there's any new contributors/rust devs that want to get familiar with the codebase, I would be willing to mentor this issue

**Comment by tyoc213** [comment]
@nicokoch I could give it a try :)

**Comment by nicokoch** [comment]
@tyoc213 Sure, ping me if there's any questions. Should be pretty easy to resolve this issue :)

**Comment by tyoc213** [comment]
Could you provide an example where I could get this Oom?, cause I already see some Error handling in the code, we have ` signaled: AtomicBool`, usage of `check_errors` and `FenceWaitError` and this note [so that we don't need to call `vkGetFenceStatus` or `vkWaitForFences`](https://github.com/tomaka/vulkano/blob/000374af5a661684f8dcc7b85e676981f3f19127/vulkano/src/sync/fence.rs#L44)


[unsafe ResetFences](https://github.com/tomaka/vulkano/blob/000374af5a661684f8dcc7b85e676981f3f19127/vulkano/src/sync/fence.rs#L267)
[checked reset fences](https://github.com/tomaka/vulkano/blob/000374af5a661684f8dcc7b85e676981f3f19127/vulkano/src/sync/fence.rs#L69)

The method comes from [ResetFences](https://github.com/tomaka/vulkano/blob/4d28294b55797d1b779e3059345fdcb7d7370b3e/vk-sys/src/lib.rs#L2765)

**Comment by nicokoch** [comment]
Sure.

The functions in question are `Fence::reset` and `Fence::multi_reset`:
https://github.com/tomaka/vulkano/blob/000374af5a661684f8dcc7b85e676981f3f19127/vulkano/src/sync/fence.rs#L264
and
https://github.com/tomaka/vulkano/blob/000374af5a661684f8dcc7b85e676981f3f19127/vulkano/src/sync/fence.rs#L278

They currently return `()`, which is wrong. They need their signatures changed to return `Result<(), OomError>`.

The second change you have to implement is actually checking for `OomError` when calling `vk::ResetFences`. This is done by wrapping the calls in `check_errors`, like here: https://github.com/tomaka/vulkano/blob/000374af5a661684f8dcc7b85e676981f3f19127/vulkano/src/sync/fence.rs#L69
