### ISSUE TITLE
Best practise for multible objects

### ISSUE THREAD

**Issue by SiebenCorgie** [tomaka/vulkano#656]
Hi,

I have a question about "best practise" for multiple different objects.
At the moment I'm using the `single_pass_renderpass!()` macro to create the renderpass and then something like this:
```
let command_buffer = {
            let mut tmp_cmd_buffer = Some(vulkano::command_buffer::AutoCommandBufferBuilder::new(device.clone(), queue.family()).expect("failed to !"));

            let build_start = tmp_cmd_buffer.take().expect("failed to take cmd buffer build for start");

            tmp_cmd_buffer = Some(build_start.begin_render_pass(
                framebuffers[image_num].clone(), false,
                vec![
                    [0.01, 0.0, 0.1, 1.0].into(),
                    1f32.into()
                ]).expect("failed to clear"));


            //Draw
                //get all meshes
            for i in root.get_all_meshes().iter(){
                let cb = tmp_cmd_buffer.take().expect("Failed to recive command buffer in loop!");
                
                tmp_cmd_buffer = Some(cb
                    .draw_indexed(
                        pipeline_01.clone(),
                        vulkano::command_buffer::DynamicState::none(),
                        i.re_create_vertex_buffer(device.clone(), queue.clone()).clone(), //normals_buffer.clone()),
                        i.get_index_buffer(device.clone(), queue.clone()).clone(),
                        set_01.clone(),
                        ()
                    ).expect("Failed to draw in command buffer!"));


            }
            //End renderpass
            tmp_cmd_buffer.take().expect("failed to return command buffer to main buffer")
        }
        .end_render_pass().expect("failed to end")
        .build().expect("failed to end");
```
to create the command buffer per frame.

The method works, but I feel like It would be better to have a subpass / pipeline(would be nice for different shaders per object) per object and attach them to the main pass depending on whats needed.

However, I didn't find a way to create a n-subpasses long `renderpass`.
My question now is: Is it possible / practical to create a renderpass per frame and attach the subpasses to it?
If not what would be the best way (in a high level overview) to render several objects with (sometimes) different shaders?

**Comment by tomaka** [comment]
Hi,
There are multiple questions here.

First of all you can draw multiple objects with multiple different pipelines in the same subpass. As far as I know most Vulkan applications don't even use multiple subpasses. They are purely an optimization that is mostly relevant on mobile.

Secondly, if you still want to create a render pass with multiple subpasses you have to use the `ordered_passes_renderpass!` macro instead of `single_pass_renderpass!`. Unfortunately it is not really documented, but the `attachments` section is the same as `single_pass_renderpass!` and you can most likely deduce the `passes` section from the macro definition.

Finally you shouldn't create a render pass per frame. There seems to be a bit of a confusion. At initialization you create one or multiple render pass objects, each of which can contain one or more subpasses. Then when drawing you *enter* each subpass of the render pass one by one (`begin_render_pass` makes you enter the first subpass). So I'm not sure what you mean by "attaching" a subpass.

**Comment by SiebenCorgie** [comment]
Hi,
thanks for the fast reply!

I thought I cant use different pipelines with the same `renderpass` because my application always crashed a while ago when I tried to clone it. However, I just tried it again and it works now!

So what I'll do now is 

1. create a render pass
2. for each mesh, create a pipeline from the device, queue and renderpass
3. draw each mesh within the first (and only) subpass

This works good for my simple forward renderer at the moment. But I guess for a forward+ (maybe deferred as well) I still would have to setup a custom renderpass. I read somewhere that you can't mix computing and graphics in one subpass.

**Comment by tomaka** [comment]
> for each mesh, create a pipeline from the device, queue and renderpass

Sorry if this is obvious but create one pipeline for each kind of mesh, not each mesh. You can draw multiple meshes from the same pipeline. Also pipelines should be created at initialization as well.

> I still would have to setup a custom renderpass

Keep in mind that subpasses have very limited usages. All the subpasses use the same framebuffer, so you can't change the dimensions. You also can only read attachments only at the current pixel in the same fragment shader, so you can't have a subpass for a gaussian blur for example.

The main point of using multiple subpasses is to give a hint to the implementation that it can draw several subpasses simultaneously, and that attachments can live in cache instead of video memory for the duration of the render pass.

**Comment by SiebenCorgie** [comment]
Okay, as far as I understand it, I should group similar meshes (for instance by material) and create a pipeline for each material. Then draw them all in the one subpass.

If I wanted to create a more sophisticated render with a depth pre-pass etc. I would have to create several main-passes and chain them. (I am mostly thinking of something like [that](https://takahiroharada.files.wordpress.com/2015/04/forward_plus.pdf), but this is far off in the future :D)

Thanks fo your help, I love Vulkano so far!

**Comment by SiebenCorgie** [comment]
Okay, as far as I understand it, I should group similar meshes (for instance by material) and create a pipeline for each material. Then draw them all in the one subpass.

If I wanted to create a more sophisticated render with a depth pre-pass etc. I would have to create several main-passes and chain them. (I am mostly thinking of something like [that](https://takahiroharada.files.wordpress.com/2015/04/forward_plus.pdf), but this is far off in the future :D)

Thanks fo your help, I love Vulkano so far!
